---

# Example variable for collected facts
collected_facts: {}

# main common vars space for the server_check_role
report_dir: /home/smaginnity/report_output/
report_file: "server_check_report.json"

check_project_version: 1.1.101

os_tag_mapping:
  RedHat: redhat
  Solaris: solaris

end_of_support: unknown # default fact value if distro is not supported by the task
redhat_ess: 7 # ends June 30, 2024
ubuntu_ess: 22.10 # ends July 2023
ubuntu_lts_ess: 18.04 # ends April 2023
suse_ess: 12 # ends 31 Oct 2024

end_of_life: unknown # default fact value if distro is not supported by the task
redhat_eol: 6 # ends June 30, 2024
ubuntu_eol: 22.10 # ends July 2023
ubuntu_lts_eol: 14.04 # ends April 2024
suse_eol: 12 # ends 31 Oct 2027


#
# Report fields for output_v2.csv.j2
# For automated collection set field_name to the field name in the compliance_data dictionary
# For manual fields set is_manual to true
#

report_fields:
  - label: "Host"
    field_name: "hostname"
  - label: "IPv4"
    field_name: "ipv4_address"
  - label: "IPv6"
    field_name: "ipv6_address"
  - label: "O/S Type"
    field_name: "os_type"
  - label: "Running Kernel"
    field_name: "running_kernel_version"
  - label: "Latest Installed Kernel"
    field_name: "latest_installed_kernel"
  - label: "Patch method"
    is_manual: true
  - label: "Patch master"
    is_manual: true
  - label: "Patch Repository"
    field_name: "audit_repolist"
  - label: "SSH permit root login"
    field_name: "ssh_permit_root_login"
  - label: "Last Patch Date"
    field_name: "last_patch_date"
  - label: "End Of Support"
    field_name: "end_of_support_bool"
  - label: "End Of Life"
    field_name: "end_of_life_bool"
  - label: "Subscribed"
    is_manual: true
  - label: "Samba Version"
    field_name: "samba_version"
  - label: "Samba Shares"
    field_name: "samba_shares"
  - label: "SELinux State"
    field_name: "selinux_status"
  - label: "SELinux Mode"
    field_name: "selinux_mode"
  - label: "SELinux Config Mode"
    field_name: "selinux_config_mode"
  - label: "NFS Exports"
    field_name: "nfs_exports"
  - label: "NFS Mounts"
    field_name: "nfs_mounts"
  - label: "Root Last Changed"
    field_name: "root_last_changed"
  - label: "Root Last Login"
    field_name: "root_last_login"
  - label: "Package Manager"
    field_name: "package_manager"
  - label: "winbind service status"
    field_name: "winbind_service_status"
  - label: "winbind domain"
    field_name: "winbind_domain"
  - label: "Auth method"
    is_manual: true
  - label: "Central auth method"
    is_manual: true
  - label: "Central auth groups"
    is_manual: true
  - label: "Generic account used by staff"
    is_manual: true
  - label: "Generic only for emergency"
    is_manual: true
  - label: "Password rotation policy"
    is_manual: true
  - label: "Firewall Running"
    field_name: "firewall_running"
  - label: "Active Firewall"
    field_name: "firewall_service_list"
  - label: "Open VM Tools"
    field_name: "open_vm_tools"
  - label: "Vmtoolsd Version"
    field_name: "vmtoolsd_version"
  - label: "External logging"
    field_name: "external_logging"
  - label: "Kernel patched during patching"
    is_manual: true
  - label: "Uptime"
    field_name: "server_uptime"
  - label: "Access method"
    is_manual: true
  - label: "As built"
    is_manual: true
  - label: "Design Docs"
    is_manual: true
  - label: "httpd info"
    field_name: "httpd_version"
  - label: "Sudo Users"
    field_name: "sudo_users"
  - label: "Sudo Groups"
    field_name: "sudo_groups"
  - label: "NTP Sources"
    field_name: "ntp_sources"
  - label: "Nameservers"
    field_name: "nameservers"
...

