---
# vars file for firewall_check
time_cmd: 'chronyc sources'
time_service: 'chronyd.service'
time_check_regex: '\^\*.*'
firewall_cmd: 'iptables'
iptables_service: 'iptables'
iptables_package: iptables
selinux_cmd: 'getenforce'
selinux_check_regex: 'Enforcing'
repo_cmd: 'dnf repolist --quiet'
iptables_sysv: 'iptables'
ufw_sysv: 'ufw'
firewalld_sysv: 'firewalld'
nftables_sysv: 'nftables'

# SAR-related vars
sar_package: sysstat
sar_config: '/usr/lib64/sa/sa1'
