---

- name: Run a task to Gather Facts and run custom tests across the Inventory of servers
  hosts: localhost
  gather_facts: true

  pre_tasks:
    - name: Configure the local instance with the packages we need
      ansible.builtin.pip:
        name: deepdiff
        state: present

  roles:
    - diff_report_files
