---

# This playbook generates a Server Status report with included output from all the standard and custom check sub tasks.
- name: Server_check_role - output_report | A block that is delegated to localhost and set to run once
  delegate_to: localhost
  run_once: true
  block:
    # This task creates the directory on the localhost to store the output report.
    - name: Server_check_role - output_report | Create output destination directory
      become: true
      ansible.builtin.file:
        path: "{{ report_dir }}"
        state: directory
        mode: '0764'
        owner: "{{ output_owner }}"
        group: "{{ output_group }}"

    # Debug to output the data from the custom tests and standard tests
    - name: Server_check_role - output_report | Debug of vars in all the places
      ansible.builtin.debug:
        var: server_report_data

    - name: Server_check_role - output_report | Run the Template Task to create the report.json file and output  # noqa: var-naming[no-role-prefix]
    # This task templates the report.json file from the compliance report data mentioned in the j2 file
      become: true
      ansible.builtin.template:
        src: "report.json.j2"
        dest: "{{ report_dir }}{{ report_state_input }}_{{ report_file }}"
        mode: '0744'
        owner: "{{ output_owner }}"
        group: "{{ output_group }}"
      register: report_output_file
      loop: "{{ play_hosts }}"
      loop_control:
        loop_var: host

    - name: Server_check_role - output_report | Show the output path
      ansible.builtin.debug:
        msg: "A new report has been generated with output at {{ report_output_file.dest }}"
      when: report_output_file.dest is defined
