---

- name: Add hostname to server_report_data
  ansible.builtin.set_fact:
    server_report_data: "{{ server_report_data | default({}) | combine(data_var) }}"
  vars:
    data_var:
      hostname: "{{ ansible_facts.fqdn }}"

...
