---
# tasks file for getting a list of all enabled repos URLs

# RHEL
- name: Check repolist (yum)
  when: ansible_os_family == "RedHat"
  block:
    - name: Check for enabled repos
      ansible.builtin.shell: |
        set -o pipefail
        awk -F'/' '/^Repo-baseurl/ { print $3}'<<<$(yum repolist -v enabled 2>&1)|uniq
      args:
        executable: /bin/bash
        creates: /tmp/enabled_yum_repos_output.tmp
        warn: false
      changed_when: false
      register: yum_repolist

    - name: Set fact based on returned value
      ansible.builtin.set_fact:
        repolist: "{{ yum_repolist.stdout | regex_replace('^ ', '') }}"
      when: yum_repolist.stdout is defined and yum_repolist.stdout

# DEBIAN / UBUNTU
- name: Check repolist (apt)
  when: ansible_os_family in ['Debian','Ubuntu']
  block:
    - name: Check for enabled repos
      ansible.builtin.shell: |
        set -o pipefail
        grep -rhE ^deb /etc/apt/sources.list*|awk '{print $2}'|uniq
      args:
        executable: /bin/bash
        creates: /tmp/enabled_apt_repos_output.tmp
        warn: false
      changed_when: false
      register: apt_repolist

    - name: Set fact based on returned value
      ansible.builtin.set_fact:
        repolist: "{{ apt_repolist.stdout | regex_replace('^ ', '') }}"
      when: apt_repolist.stdout is defined and apt_repolist.stdout

# SUSE
- name: Check repolist (zypper)
  when: ansible_os_family == "Suse"
  block:
    - name: Check for enabled repos
      ansible.builtin.shell: |
        set -o pipefail
        zypper repos -d|awk -F'|' '// {print $9}'
      args:
        executable: /bin/bash
        creates: /tmp/enabled_zypper_repos_output.tmp
        warn: false
      changed_when: false
      register: zypper_repolist

    - name: Set fact based on returned value
      ansible.builtin.set_fact:
        repolist: "{{ zypper_repolist.stdout | regex_replace('^ ', '') }}"
      when: zypper_repolist.stdout is defined and zypper_repolist.stdout

- name: Add repolist to server_report_data
  ansible.builtin.set_fact:
    server_report_data: "{{ server_report_data | default({}) | combine(data_var) }}"
  vars:
    data_var:
      audit_repolist: "{{ repolist | default('No repos enabled') }}"

...
