---

- name: Set basic facts for hostname etc
  ansible.builtin.set_fact:
    hostname: "{{ ansible_fqdn }}"
    ip_address: "{{ ansible_default_ipv4.address }}"
    kernel_version: "{{ ansible_kernel }}"
    os_release: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Gather installed software facts
  ansible.builtin.package_facts:
    manager: "{{ ansible_pkg_mgr }}"
  register: software_facts

- name: Gather hardware facts
  ansible.builtin.setup:
    filter: ansible_product_name
  register: hardware_facts

- name: Get list of current users logged in
  ansible.builtin.command: "who"
  register: who_output
  changed_when: who_output.stdout != ansible_facts.who.stdout | default('')
  check_mode: false

- name: Get current grub config
  ansible.builtin.command: "cat /etc/default/grub"
  register: grub_output
  changed_when: false
  check_mode: false

- name: Get current fstab information
  ansible.builtin.command: "cat /etc/fstab"
  register: fstab_output
  changed_when: false
  check_mode: false

- name: Get current swap devices and usage
  ansible.builtin.command: "free -h | grep Swap"
  register: swap_output
  changed_when: false
  check_mode: false

- name: Get current route information
  ansible.builtin.command: "ip route show"
  register: route_output
  changed_when: false
  check_mode: false

- name: Format output
  ansible.builtin.set_fact:
    uptime: "{{ uptime_output.stdout }}"
    logged_in_users: "{{ who_output.stdout_lines }}"
    grub_config: "{{ grub_output.stdout }}"
    fstab_config: "{{ fstab_output.stdout }}"
    disk_usage: "{{ disk_usage_output.stdout }}"
    swap: "{{ swap_output.stdout }}"
    route_info: "{{ route_output.stdout }}"
