---

- name: Add IPV4 address to server_report_data
  ansible.builtin.set_fact:
    server_report_data: "{{ server_report_data | default({}) | combine(additional_data) }}"
  vars:
    additional_data:
      ipv4_address: "{{ ansible_facts.default_ipv4.address | default('ipv4 address not found') }}"

...
