---

- name: Add IPV4 address to server_report_data
  ansible.builtin.set_fact:
    server_report_data: "{{ server_report_data | default({}) | combine(data_var) }}"
  vars:
    data_var:
      ipv4_address: "{{ ansible_facts.default_ipv4.address | default('ipv4 address not found') }}"

...
