---

- name: Set nfs_mounts_list fact
  ansible.builtin.set_fact:
    nfs_mounts_list: "{{ nfs_mounts_list | default([]) + [nfs_item.fstype + ': ' + nfs_item.mount + ' from ' + nfs_item.device] }}"
  loop: "{{ ansible_mounts }}"
  when:
    - '"nfs" in nfs_item.fstype'
  loop_control:
    loop_var: nfs_item

- name: "Add output of yml file to the server_report_data and output / combine it into additional data"
  ansible.builtin.set_fact:
    server_report_data: "{{ server_report_data | default({}) | combine(additional_data) }}"
  vars:
    additional_data:
      nfs_mounts: "{{ nfs_mounts_list | default | join('\n') }}"

...
