---

- name: Get details of open_vm_tools package
  ansible.builtin.set_fact:
    __open_vm_tools: "{{ __open_vm_tools |
      default([]) + ['%s-%s.%s' | format(pkg_data.version, pkg_data.release |
      default(omit), pkg_data.arch)] }}"  # noqa 204
  loop: "{{ ansible_facts.packages[open_vm_tools_package] | default([]) }}"
  loop_control:
    loop_var: pkg_data

- name: "Add output of yml file to the server_report_data and combine it with the data_var"
  ansible.builtin.set_fact:
    server_report_data: "{{ server_report_data | default([]) | combine(data_var) }}"
  vars:
    data_var:
      open_vm_tools: "{{ __open_vm_tools | default(['Not Installed']) | join('\n') }}"

...
