---

- name: Add ostype to server_report_data
  ansible.builtin.set_fact:
    server_report_data: "{{ server_report_data | default({}) | combine(data_var) }}"
  vars:
    data_var:
      os_type: "{{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}"

...
