---

- name: Execute 'last -1 -R root | head -1 | awk '{print $4 ,$5 ,$6}'' checks for last root login
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    last -1 -R root | head -1 | awk '{print $4, $5, $6}'
  args:
    executable: /bin/bash
    warn: false
  register: __root_last_login
  changed_when: false
  failed_when: "__root_last_login.rc == -1"
  # Hack to make the task return "changed"

- name: "Add output of yml file to the server_report_data and combine it with the data_var"
  ansible.builtin.set_fact:
    server_report_data: "{{ server_report_data | default({}) | combine(data_var) }}"
  vars:
    data_var:
      root_last_login: "{{ __root_last_login.stdout | trim | default }}"

...
