---

- name: Add kernel version to server_report_data
  ansible.builtin.set_fact:
    server_report_data: "{{ server_report_data | default({}) | combine(additional_data) }}"
  vars:
    additional_data:
      running_kernel_version: "{{ ansible_facts.kernel }}"

...
