---

# - name: Gather installed software facts
#   ansible.builtin.package_facts:
#     manager: "{{ lookup('pipe', 'if which dnf > /dev/null 2>&1; then echo dnf;
#       elif which yum > /dev/null 2>&1; then echo yum;
#       elif which apt-get > /dev/null 2>&1; then echo apt;
#       elif which apk > /dev/null 2>&1; then echo apk;
#       else echo unknown; fi') }}"
#   register: software_facts

# - name: Check if package manager is supported
#   ansible.builtin.fail:
#     msg: "Unsupported package manager: {{ software_facts['manager'] }}"
#   when: "'manager' not in software_facts or software_facts['manager'] == 'unknown'"

- name: Display installed software
  ansible.builtin.debug:
    var: ansible_facts.packages

- name: "Add output of software information into the server_report_data and combine it with the data_var"
  ansible.builtin.set_fact:
    server_report_data: "{{ server_report_data | default({}) | combine(data_var) }}"
  vars:
    data_var:
      ansible_package_info: "{{ ansible_package_info | default('Package Information not found') }}"


...
