---

- name: Set Fact for the server uptime
  ansible.builtin.set_fact:
    __server_uptime: "{{ now().replace(microsecond=0) - now().fromtimestamp(now(fmt='%s') | int - ansible_uptime_seconds) }}"

- name: Add the server uptime to the server output report
  ansible.builtin.set_fact:
    server_report_data: "{{ server_report_data | default({}) | combine(additional_data) }}"
  vars:
    additional_data:
      server_uptime: "{{ __server_uptime | default('uptime not discovered') }}"
