- name: Get uptime information
  ansible.builtin.shell: |
    case "{{ ansible_facts['os_family'] }}" in
      'RedHat') uptime ;;
      'AIX') uptime -s ;;
      'Solaris') uptime ;;
      *) echo "Unsupported OS" ;;
    esac
  register: uptime_output
  changed_when: false
  check_mode: false
