---

- name: Run custom file comparison  # noqa: var-naming[no-role-prefix]
  compare_files:
    before_file: "{{ diff_before_file }}"
    after_file: "{{ diff_after_file }}"
    ignore_list: "{{ diff_ignore_list }}"
  register: compare_result

- name: Display the entire results file  # noqa: var-naming[no-role-prefix]
  ansible.builtin.debug:
    var: compare_result
  tags:
    - debug
    - never

- name: Output diff to file  # noqa: var-naming[no-role-prefix]
  ansible.builtin.copy:
    content: "{{ diff_content }}"
    dest: "{{ diff_output_file }}"
    mode: '0644'
  vars:
    diff_content: "{{ compare_result.result.differences | to_nice_json }}"
  when: compare_result.result.differences is defined and compare_result.result.differences | length > 0
