---

- name: Read 'before' report file  # noqa: var-naming[no-role-prefix]
  ansible.builtin.slurp:
    src: "/path/to/before_report.json"
  register: before_report_file

- name: Read 'after' report file  # noqa: var-naming[no-role-prefix]
  ansible.builtin.slurp:
    src: "/path/to/after_report.json"
  register: after_report_file

- name: Compare files and ignore specific changes  # noqa: var-naming[no-role-prefix]
  ansible.builtin.assert:
    that:
      - before_report_file['content'] | b64decode | from_json != after_report_file['content'] | b64decode | from_json
    quiet: true
    success_msg: "Files are identical"
    fail_msg: "Files differ"
    diff_msg: "Diff:"
    ignore_lines: "{{ ignore_lines }}"
  vars:
    ignore_lines:
      - ".*disk_size.*"
      - ".*date.*"
