---

- name: Run custom file comparison  # noqa: var-naming[no-role-prefix]
  compare_files:
    before_file: "{{ report_dir }}before_{{ report_file }}"
    after_file: "{{ report_dir }}after_{{ report_file }}"
  register: compare_result
  vars:
    ignore_list:
      - "['server_report_data'][0]['ansible_facts']['date_time']['date']"
      - "['server_report_data'][0]['ansible_facts']['date_time']['day']"
      - "['server_report_data'][0]['ansible_facts']['date_time']['epoch']"
      - "['server_report_data'][0]['ansible_facts']['date_time']['epoch_int']"

- name: Display differences  # noqa: var-naming[no-role-prefix]
  ansible.builtin.debug:
    var: compare_result.result.differences
  tags:
    - debug
    - never

- name: Output diff to file
  ansible.builtin.copy:
    content: "{{ diff_content }}"
    dest: "{{ report_dir }}diff_output.json"
  vars:
    diff_content: "{{ compare_result.result.differences | to_nice_json }}"
  when: compare_result.result.differences is defined and compare_result.result.differences | length > 0
