---

- name: Diff Role - Main | Read 'before' report file  # noqa: var-naming[no-role-prefix]
  ansible.builtin.slurp:
    src: "{{ report_dir }}before_{{ report_file }}"
  register: before_report_file

- name: Diff Role - Main | Read 'after' report file  # noqa: var-naming[no-role-prefix]
  ansible.builtin.slurp:
    src: "{{ report_dir }}after_{{ report_file }}"
  register: after_report_file

- name: Diff Role - Main | Compare files and ignore specific changes  # noqa: var-naming[no-role-prefix]
  ansible.builtin.assert:
    that:
      - before_report_file['content'] | b64decode | from_json != after_report_file['content'] | b64decode | from_json
    quiet: true
    success_msg: "Files are identical"
    fail_msg: "Files differ"
    diff_msg: "Diff:"
    ignore_lines: "{{ ignore_lines }}"
  vars:
    ignore_lines:
      - ".*disk_size.*"
      - ".*date.*"
