---

- name: Ensure that our required python pip module deepdiff is installed
  ansible.builtin.pip:
    name: deepdiff
    state: present
  delegate_to: localhost

- name: Run the custom python library file to do a file comparison for the before and after files  # noqa: var-naming[no-role-prefix]
  compare_files:
    before_file: "{{ diff_before_file }}"
    after_file: "{{ diff_after_file }}"
    ignore_list: "{{ diff_ignore_list }}"
  register: compare_result
  delegate_to: localhost
  
- name: Display the entire results file  # noqa: var-naming[no-role-prefix]
  ansible.builtin.debug:
    var: compare_result
  tags:
    - debug
    - never
  delegate_to: localhost

- name: Display the ignore list from the python compare module  # noqa: var-naming[no-role-prefix]
  ansible.builtin.debug:
    var: compare_result.result.ignore_list
  tags:
    - debug
    - never
  delegate_to: localhost

- name: Display the ignored paths from the python compare module  # noqa: var-naming[no-role-prefix]
  ansible.builtin.debug:
    var: compare_result.result.ignored_paths
  tags:
    - debug
    - never
  delegate_to: localhost

- name: Output diff to file  # noqa: var-naming[no-role-prefix]
  ansible.builtin.copy:
    content: "{{ diff_content }}"
    dest: "{{ diff_output_file }}"
    mode: '0644'
  vars:
    diff_content: "{{ compare_result.result.differences | to_nice_json }}"
  when: compare_result.result.differences is defined and compare_result.result.differences | length > 0
  delegate_to: localhost

# Consider adding the following to some sort of task rescue block if the output to diff task above fails for any reason
# - name: Install pyenv
#   git:
#     repo: https://github.com/pyenv/pyenv.git
#     dest: ~/.pyenv
#     version: master
#   become: yes

# - name: Configure pyenv
#   lineinfile:
#     dest: ~/.bashrc
#     line: 'export PYENV_ROOT="$HOME/.pyenv"'
#   become: yes

# - name: Install Python 3.8.12 using pyenv
#   shell: pyenv install 3.8.12
#   become: yes
#   args:
#     executable: /bin/bash
#     creates: ~/.pyenv/versions/3.8.12
