---

name: ansible-lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Ansible Lint
        uses: ansible/ansible-lint-action@v5.1.0
        with:
          args: -p roles/**/*.yml main_playbook.yml --exclude=roles/junos_*

      - name: Syntax check
        run: ansible-playbook --syntax-check main_playbook.yml

...
